ABF-3282: Fix TFSA ceiling projections
kronostechnologies/tax-ca pull request #104
Opened 2021-01-25 19:34 UTC by JsGarneau

Suite à un talk avec Kev, il était préférable d'utiliser la valeur qui n'est pas rounded pour appliquer l'inflation. Donc nous nous sommes fier au tableau dans la carte pour prendre la dernière valeur qui à changé (5500 -> 6000) et nous avons pris la valeur qui n'était pas rounded up (5847.32)

2021-01-26 20:16 UTC, jeremilc approved these changes

2021-01-27 13:55 UTC, Pierregagne approved these changes

2021-01-27 14:03 UTC, Pierregagne commented on src/investments/tax-free-savings-account.ts
> +    UPDATE_YEAR: 2019,
@JsGarneau Je ne comprend pas pourquoi on change la valeur de `MAX_CONTRIBUTION`. Si on check pour l'année 2019, c'est 6000 et non 5850. Ce n'est pas assez de prendre en compte l'année (2019) dans plan?

2021-01-27 14:12 UTC, Pierregagne requested changes
^ J'ai l'impression qu'il faudrait avoir 2 valeurs. Une pour ce qui est arrondi & affiché par le gouv. (6000) et une autre qui n'est pas arrondi pour notre indexation (5850).

2021-01-27 17:02 UTC, toby-daigle approved these changes

2021-01-27 20:48 UTC, JsGarneau commented on src/investments/tax-free-savings-account.ts
> +    UPDATE_YEAR: 2019,
https://jira.equisoft.com/secure/attachment/179691/Classeur1.png

Si on regarde le graphique de Kev, l'année 2019, où on passe de 5500 à 6000, on a en fait une valeur de 5850~ qu'on round up à 6000, en appliquant l'inflation en plus à partir e 2019 sur 6000$, la projection est trop élevé et donne un résultat trop optimiste et on aurait changé de bracket (6500) trop tôt

2021-01-27 21:45 UTC, Pierregagne commented on src/investments/tax-free-savings-account.ts
> +    UPDATE_YEAR: 2019,
Mon point c'est plus pour les gens qui vont utiliser tax-ca pour la valeur actuelle qui est 6000. C'est ce qui fit la source du fichier https://www.canada.ca/en/revenue-agency/services/tax/registered-plans-administrators/pspa/mp-rrsp-dpsp-tfsa-limits-ympe.html

5850 sers a compenser une lacune dans nos projections et ça devrait être dans une variable séparé IMO. Genre `MAX_COUNTRIBUTION_UNROUNDED`

2021-01-28 13:34 UTC, Pierregagne approved these changes

2021-01-28 13:35 UTC, merged