ABF-3346 : Simplification calcul de l'impot et ajout du taux effectif
kronostechnologies/tax-ca pull request #115
Opened 2021-04-09 14:08 UTC by julienchouinard

Valider le calcul du taux effectif
Valider le calcul simplifié des taxes.

2021-04-09 15:14 UTC, toby-daigle requested changes

2021-04-09 15:14 UTC, toby-daigle commented on src/taxes/income-tax.ts
> +    return Math.max(baseTaxAmount - baseCredit, 0) + surTax;
Pour calculer la surtax, tu dois prendre `baseTaxAmount - baseCredit`
```suggestion
    const baseTaxAmount = getProvincialBaseTaxAmount(province, grossIncome, inflationRate, yearsToInflate);
    const baseCredit = getProvincialBaseCredit(province, inflationRate, yearsToInflate);
    const tax = Math.max(baseTaxAmount - baseCredit, 0)
    const surTax = getProvincialSurtaxAmount(province, tax, inflationRate, yearsToInflate);
    return tax + surTax;
```

2021-04-09 15:14 UTC, toby-daigle commented on src/taxes/income-tax.ts
> +    const abatement = getProvincialAbatement(provincialCode, fedTax);
Même si on parle de _Provincial abatement_, ça fait parti de la portion fédéral des impôts. Donc, même si on est obligé d'ajouter un paramètre pour ta province, je crois quand même qu'on devrait mettre le calcul de l'abatement dans la fonction `getFederalTaxAmount `

2021-04-09 15:14 UTC, toby-daigle commented on src/taxes/income-tax.ts
>      }
J'aime les opérations ternaire
```suggestion
        return income <= 0 ? 0 : (getTotalTaxAmount(province, income, inflationRate, yearsToInflate)) / income;
```

2021-04-09 15:14 UTC, toby-daigle commented on src/taxes/income-tax.ts
> +export function getEffectiveRate(
Pourquoi cette nouvelle fonction ? ne devrait-on pas simplement renommer `calculateEffectiveTaxRate` pour `getEffectiveTaxRate`

2021-04-09 15:14 UTC, toby-daigle commented on src/taxes/income-tax.ts
> +    yearsToInflate = 0,
Je crois qu'on devrait changer l'ordre des paramètres pour que ça ressemble plus au autres fonctions
```suggestion
    province: ProvinceCode,
    income: number,
    inflationRate = 0,
    yearsToInflate = 0,
```

2021-04-09 15:15 UTC, toby-daigle commented on src/taxes/income-tax.ts
> +    yearsToInflate = 0,
Par contre, puisque la fonction est utilisé dans express, idéalement faudrait que lorsqu'on bump la version dans express, on fasse attention de bien corriger cela.

2021-04-09 16:51 UTC, julienchouinard commented on src/taxes/income-tax.ts
> +export function getEffectiveRate(
c'est mon TOC, les autres sont tous des "getQuelquechose", mais calculate existait déjà.

2021-04-09 16:52 UTC, julienchouinard commented on src/taxes/income-tax.ts
> +    yearsToInflate = 0,
Ouais j'avais remarqué et je ne l'ai pas changé pour les effets "incontrôlé" d'inverser les paramêtres. On peut se gâter si t'es confiant.

2021-04-09 16:53 UTC, julienchouinard commented on src/taxes/income-tax.ts
> +    return Math.max(baseTaxAmount - baseCredit, 0) + surTax;
Je l'ai rechangé ce matin vers la version que j'ai fait un commit, j'avais une différence de valeur produite par rapport à l'accept. Je vais valider de nouveau.

2021-04-09 18:05 UTC, toby-daigle commented on src/taxes/income-tax.ts
> +    yearsToInflate = 0,
Je suis confiant, les gens qui font un update on juste à checker leurs affaires

2021-04-09 18:05 UTC, toby-daigle commented on src/taxes/income-tax.ts
> +export function getEffectiveRate(
Je suis d'accord, alors on peut renomme `calculate` pour `get`

2021-04-14 13:02 UTC, julienchouinard commented on src/taxes/income-tax.ts
>      }
Moi moins :P

2021-04-14 15:52 UTC, toby-daigle approved these changes
THIS LOOKS AWESOME!

2021-04-14 15:54 UTC, merged